name: Weekly Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get Version Number
      uses: fwilhe2/bump-version@main
      id: bump
      with:
        component:  minor
    - run: echo New Version Number ${{ steps.bump.outputs.newVersion }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump.outputs.newVersion }}
        release_name: Release ${{ steps.bump.outputs.newVersion }}
        draft: false
        prerelease: false

    - name: Build image
      run: docker build . --file Dockerfile --tag fwilhe2/speedtest:${{ steps.bump.outputs.newVersion }}

    - name: Log into DockerHub
      run: echo "${{ secrets.DH_PAT }}" | docker login -u fwilhe2 --password-stdin

    - name: Push image
      run: |
        docker push fwilhe2/speedtest:${{ steps.bump.outputs.newVersion }}
        docker tag fwilhe2/speedtest:${{ steps.bump.outputs.newVersion }} fwilhe2/speedtest:latest
        docker push fwilhe2/speedtest:latest

    - uses: anchore/sbom-action@v0
      with:
        image: fwilhe2/speedtest:${{ steps.bump.outputs.newVersion }}

    - uses: anchore/sbom-action/publish-sbom@v0
      with:
        sbom-artifact-match: ".*\\.spdx$"